apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: deny-all
  namespace: {{ .Release.Namespace}}
spec:
  {}
---
apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: fridge-client-policy
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app_client_name }}-service
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
    - to:
        - operation:
            methods: ["GET"]
            ports: ["80"]
---
apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: fridge-api-policy
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: {{ .Values.app_api_name }}-service
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"]
    - to:
        - operation:
            methods: ["GET", "POST", "PUT", "DELETE"]
            ports: ["5000"]
---
apiVersion: "security.istio.io/v1beta1"
kind: AuthorizationPolicy
metadata:
  name: db-service-policy
  namespace: {{ .Release.Namespace}}
spec:
  selector:
    matchLabels:
      app: db-service
  action: ALLOW
  rules:
    - from:
        - source:
            principals: ["cluster.local/ns/{{ .Release.Namespace}}/sa/db-access"]
    - to:
        - operation:
            ports: ["5432"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-system
  namespace: {{ .Release.Namespace}}
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["istio-system"]
---
