apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-service
  name: db-service
spec:
  externalName: {{ .Values.env.database.url}}
  selector:
    app: db-service
  type: ExternalName
status:
  loadBalancer: {}