apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  password: {{ .Values.env.database.password | b64enc | quote}}
  username: {{ .Values.env.database.username | b64enc | quote}}